# Generated by Django 5.2.7 on 2025-11-05 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_ml', models.PositiveIntegerField(verbose_name='السعة (مل)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='home.perfume')),
            ],
        ),
    ]
