# Generated by Django 5.2.7 on 2025-11-05 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_perfumesize'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perfume_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.perfumesize')),
            ],
        ),
    ]
