# Generated by Django 5.2.7 on 2025-11-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='gender',
            field=models.CharField(choices=[('M', 'رجالي'), ('F', 'حريمي'), ('U', 'يونيسكس (للجنسين)')], default='U', max_length=1, verbose_name='النوع'),
        ),
    ]
