# Generated by Django 5.2.7 on 2025-11-06 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cartitem_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='gender',
        ),
    ]
