# Generated by Django 5.2.7 on 2025-11-07 17:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_perfume_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='صورة العطر'),
        ),
    ]
