# Generated by Django 5.2.7 on 2025-11-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_perfume_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='is_original',
            field=models.BooleanField(default=False),
        ),
    ]
