# Generated by Django 5.2.7 on 2025-11-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_perfume_is_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumesize',
            name='is_original',
            field=models.BooleanField(default=False, verbose_name='إزازة أوريجينال؟'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='is_original',
            field=models.BooleanField(default=False, verbose_name='إزازة أوريجينال؟'),
        ),
    ]
