# Generated by Django 5.2.7 on 2025-11-08 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_perfumesize_is_original_alter_perfume_is_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_gift',
            field=models.BooleanField(default=False, verbose_name='هدية؟'),
        ),
    ]
