# Generated by Django 5.2.7 on 2025-11-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cartitem_added_at_cartitem_is_gift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='is_gift',
        ),
    ]
